#! /usr/bin/python

import os
from evdev import InputDevice, categorize, ecodes
from pygame import mixer
import sounddevice as sd
import soundfile as sf
from pydub import AudioSegment
from pydub.playback import play

os.chdir('/usr/local/share/keyboard')
dev = InputDevice('/dev/input/event22')
dev.grab()
mixer.init()

## Define sounds here
#yeet = mixer.Sound('sounds/yeet.wav')
#airhorn = mixer.Sound('sounds/airhorn.wav')
#error = mixer.Sound('sounds/error.wav')
#johncena = mixer.Sound('sounds/johncena.wav')
#missionfailed = mixer.Sound('sounds/missionfailed.wav')
#jokedrum = mixer.Sound('sounds/jokedrum.wav')
#nope = mixer.Sound('sounds/nope.wav')
#mynamejeff = mixer.Sound('sounds/mynamejeff.wav')
#hallelujah = mixer.Sound('sounds/hallelujah.wav')
#oof = mixer.Sound('sounds/oof.wav')

## Help function
def showhelp():
    print('')
    print('ASSIGNED KEYS')
    print('ESC: Exit program')
    print('ENTER: Show help')
    print('Q: [SOUND] yeet')
    print('W: [SOUND] airhorn')
    print('E: [SOUND] error')
    print('R: [SOUND] johncena')
    print('T: [SOUND] missionfailed')
    print('Y: [SOUND] jokedrum')
    print('U: [SOUND] nope')
    print('I: [SOUND] mynamejeff')
    print('O: [SOUND] hallelujah')
    print('P: [SOUND] oof')


## Deine keystrokes and actions
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode == 'KEY_Q':
#                yeet.play()
#                file = "yeet.mp3"
#                os.system("mpg123 --realtime " + file)
                song = AudioSegment.from_wav("yeet.wav")
                play(song)
            elif key.keycode == 'KEY_W':
                airhorn.play()
            elif key.keycode == 'KEY_E':
                error.play()
            elif key.keycode == 'KEY_R':
                johncena.play()
            elif key.keycode == 'KEY_T':
                missionfailed.play()
            elif key.keycode == 'KEY_Y':
                jokedrum.play()
            elif key.keycode == 'KEY_U':
                nope.play()
            elif key.keycode == 'KEY_I':
                mynamejeff.play()
            elif key.keycode == 'KEY_O':
                hallelujah.play()
            elif key.keycode == 'KEY_P':
                oof.play()
            elif key.keycode == 'KEY_ENTER':
                showhelp()
            elif key.keycode == 'KEY_ESC':
                quit()
            else :
                print('Unassinged Key')
