#! /usr/bin/python

import os
import webbrowser
from evdev import InputDevice, categorize, ecodes
from pygame import mixer

os.chdir('/home/luke/.local/share/keyboard')
#dev = InputDevice('/dev/input/event2')
dev = InputDevice('/dev/input/by-id/usb-NOVATEK_Kensington_U+P_Keyboard-event-kbd')
dev.grab()
mixer.init()


# Define sounds here
bind_dict = {
        'KEY_Q': 'sounds/yeet.wav',
        'KEY_W': 'sounds/ballsofsteel.wav'
        }

## Deine keystrokes and actions
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode != 'KEY_ESC':
                if 'key.keycode' in bind_dict != true:
                    print('Unassigned Key')
                bind = bind_dict[key.keycode]
                sound = mixer.Sound(bind)
                sound.play()
            else:
                quit()
#            else :
#                print('Unassinged Key')
