#! /usr/bin/python

import webbrowser
from evdev import UInput, InputDevice, categorize, ecodes

dev = InputDevice('/dev/input/by-id/usb-NOVATEK_Kensington_U+P_Keyboard-event-kbd')
dev.grab()
ui = UInput()


# Dictionary to assign keycodes to sound files
bind_dict = {
        'KEY_Q': ['web','https://www.youtube.com'],
        'KEY_W': ['placeholder','placeholder'],
        'KEY_E': ['placeholder','placeholder'],
        'KEY_R': ['placeholder','placeholder'],
        'KEY_T': ['placeholder','placeholder'],
        'KEY_Y': ['placeholder','placeholder'],
        'KEY_U': ['placeholder','placeholder'],
        'KEY_I': ['placeholder','placeholder'],
        'KEY_O': ['placeholder','placeholder'],
        'KEY_P': ['placeholder','placeholder'],
        'KEY_A': ['placeholder','placeholder'],
        'KEY_S': ['placeholder','placeholder'],
        'KEY_D': ['placeholder','placeholder'],
        'KEY_F': ['placeholder','placeholder'],
        'KEY_G': ['placeholder','placeholder'],
        'KEY_H': ['placeholder','placeholder'],
        'KEY_J': ['placeholder','placeholder'],
        'KEY_K': ['placeholder','placeholder'],
        'KEY_L': ['placeholder','placeholder'],
        'KEY_Z': ['placeholder','placeholder'],
        'KEY_X': ['input',[56,62]],
        'KEY_C': ['placeholder','placeholder'],
        'KEY_V': ['placeholder','placeholder'],
        'KEY_B': ['placeholder','placeholder'],
        'KEY_N': ['placeholder','placeholder'],
        'KEY_M': ['placeholder','placeholder'],
        }


## Loop to read input from device 
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode == 'KEY_ESC':
                quit()
            elif key.keycode == 'KEY_F12':
                print('Implement rebind function here')
            else:
                if key.keycode in bind_dict:
                    ## bind is assisgned the value of the second item in the list within the bind_dict values
                    bind = bind_dict[key.keycode][1]
                    if bind_dict[key.keycode][0] == 'input':
                        ## write the key specified in the bind_dict
                        for i in bind:
                            ui.write(ecodes.EV_KEY, i, 1)
                            ui.syn()
                        for i in bind:
                            ui.write(ecodes.EV_KEY, i, 0)
                            ui.syn()
                    elif bind_dict[key.keycode][0] == 'web':
                        webbrowser.open(bind,new=2,autoraise=True)
                    else:
                        print('Key must be a web or input type. Key is currently set to the type: ' + bind_dict[key.keycode][0])
                else:
                    print(key.keycode + ' is undefined')
