#! /usr/bin/python

import webbrowser
from evdev import UInput, InputDevice, categorize, ecodes

dev = InputDevice('/dev/input/by-id/usb-NOVATEK_Kensington_U+P_Keyboard-event-kbd')
dev.grab()
ui = UInput()


class WebBinding:
    def __init__(self, key, website):
        self.key = key
        self.website = website
    
    def action(self):
        webbrowser.open(self.website,new=2,autoraise=True)


class MacroBinding:
    def __init__(self, key, macro):
        self.key = key
        self.macro = macro

    def action(self):
        for i in x.macro:
            ui.write(ecodes.EV_KEY, i, 1)
            ui.syn()
        for i in x.macro:
            ui.write(ecodes.EV_KEY, i, 0)
            ui.syn()


q = WebBinding('KEY_Q', 'https://www.youtube.com')
x = MacroBinding('KEY_X', [56,62])

bindings = {'KEY_ESC': esc, 'KEY_F1': f1, 'KEY_F2': f2, 'KEY_F3': f3, 'KEY_F4': f4, 'KEY_F5': f5, 'KEY_F6': f6, 'KEY_F7': f7, 'KEY_F8': f8, 'KEY_F9': f9,
        'KEY_F10': f10, 'KEY_F11': f11, 'KEY_F12': f12, 'KEY_Q': q, 'KEY_W': w, 'KEY_E': e, 'KEY_R': r, 'KEY_T': t, 'KEY_Y': y, 'KEY_U': u, 'KEY_I': i, 'KEY_O': o, 'KEY_P': p, 'KEY_A': a, 'KEY_S': s, 'KEY_D': d, 'KEY_F': f, 'KEY_G': G, 'KEY_H': h, 'KEY_J': j, 'KEY_K': k, 'KEY_L': l, 'KEY_Z': z, 'KEY_X': x, 'KEY_C': c, 'KEY_V': v, 'KEY_B': b, 'KEY_N': n, 'KEY_M': m}


## Loop to read input from device 
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode == 'KEY_ESC':
                quit()
            elif key.keycode == 'KEY_F12':
                print('Implement rebind function here')
            else:
                if key.keycode in binded_keys:
                    keyobject = binded_keys[key.keycode]
                    keyobject.action()
                else:
                    print(key.keycode + ' is undefined')
