#! /usr/bin/python

import webbrowser
from evdev import UInput, InputDevice, categorize, ecodes

dev = InputDevice('/dev/input/by-id/usb-NOVATEK_Kensington_U+P_Keyboard-event-kbd')
dev.grab()
ui = UInput()


class WebBinding:
    def __init__(self, key, website):
        self.key = key
        self.website = website
    
    def action(self):
        webbrowser.open(self.website,new=2,autoraise=True)


class MacroBinding:
    def __init__(self, key, macro):
        self.key = key
        self.macro = macro

    def action(self):
        for i in x.macro:
            ui.write(ecodes.EV_KEY, i, 1)
            ui.syn()
        for i in x.macro:
            ui.write(ecodes.EV_KEY, i, 0)
            ui.syn()


q = WebBinding('KEY_Q', 'https://www.youtube.com')
x = MacroBinding('KEY_X', [56,62])

binded_keys = {'KEY_Q': q, 'KEY_X': x}


## Loop to read input from device 
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode == 'KEY_ESC':
                quit()
            elif key.keycode == 'KEY_F12':
                print('Implement rebind function here')
            else:
                if key.keycode in binded_keys:
                    keyobject = binded_keys[key.keycode]
                    keyobject.action()
                else:
                    print(key.keycode + ' is undefined')
