#! /usr/bin/python

import webbrowser
from evdev import UInput, InputDevice, categorize, ecodes

dev = InputDevice('/dev/input/by-id/usb-NOVATEK_Kensington_U+P_Keyboard-event-kbd')
dev.grab()
ui = UInput()


# Dictionary to assign keycodes to sound files
bind_dict = {
        'KEY_Q': ('web','https://www.youtube.com'),
        'KEY_W': ('input','press A'),
        'KEY_E': ('input','press B')
        }


## Define keystrokes and actions
for event in dev.read_loop():
    if event.type == ecodes.EV_KEY:
        key = categorize(event)
        if key.keystate == key.key_down:
            if key.keycode == 'KEY_ESC':
                quit()
            elif key.keycode == 'KEY_F12':
                print('Implement rebind function here')
            else:
                if key.keycode in bind_dict:
                    bind = bind_dict[key.keycode][1]
                    if bind_dict[key.keycode][0] == 'input':
                        print('Implement input')
#                        keypress = 
#                        ui.write(ecodes.EV_KEY, key.scancode, 1)
#                        ui.write(ecodes.EV_KEY, key.scancode, 0)
                    elif bind_dict[key.keycode][0] == 'web':
                        webbrowser.open(bind,new=2,autoraise=True)
                else:
                    print(key.keycode + ' is undefined')
